export type NormalizedMetrics = {
  dateRange: string;
  revenue: number;
  orders: number;
  aov: number;
  adSpend: number;
  roas: number;
  conversionRate: number;
  sessions?: number;
  sessionsSourceLabel?: string;
  sessionsProductionReady?: boolean;
  sessionsNote?: string;
  reachEstimate?: number;
  reachEstimateProductionReady?: boolean;
  reachEstimateSource?: string;
  reachEstimateNote?: string;
  attribution: Record<string, number>;
  channelSpend?: Record<string, number>;
  attributionNote?: string;
  lastSyncedAt: string;
  source: string;
  sourceNote?: string;
  sourceStatus?: string;
  productionReady?: boolean;
  coreMetricsProductionReady?: boolean;
  attributionProductionReady?: boolean;
  platformConversionValue?: number;
  platformConversionSources?: string[];
  platformConversionLabel?: string;
  platformConversionProductionReady?: boolean;
  platformConversionNote?: string;
  conversionRateProductionReady?: boolean;
  conversionRateStatus?: string;
  conversionRateNote?: string;
  sourceWarning?: string | null;
  autoRefresh?: { attempted: boolean; ok: boolean; reason: string; error?: string };
  snapshotId?: string;
  provider?: string;
  mapping?: Record<string, unknown>;
};

export type MetricsSnapshotRow = {
  id: string;
  workspace_id: string;
  provider: string;
  date_range: string;
  raw_payload: Record<string, unknown>;
  normalized_metrics: NormalizedMetrics;
  source_started_at: Date | null;
  source_ended_at: Date | null;
  created_at: Date;
};
