import { Router } from 'express';
import { env } from '../config/env.js';
import { healthRouter } from '../modules/health/health.routes.js';
import { metricsRouter } from '../modules/metrics/metrics.routes.js';
import { chatRouter } from '../modules/chat/chat.routes.js';
import { claudeRouter } from '../modules/ai/claude.routes.js';
import { briefRouter, weeklyRouter } from '../modules/briefs/briefs.routes.js';
import { adminRouter } from '../modules/admin/admin.routes.js';
import { databaseRouter } from '../modules/database/database.routes.js';
import { authRouter } from '../modules/auth/auth.routes.js';
import { authRequired } from '../common/middleware/auth-required.js';
import { optionalAuth } from '../common/middleware/optional-auth.js';
import { tripleWhaleConnectionRouter } from '../modules/connected-accounts/connected-accounts.routes.js';
import { refreshMetricsRouter, tripleWhaleRouter } from '../modules/triple-whale/triple-whale.routes.js';
import { draftsRouter } from '../modules/drafts/drafts.routes.js';
import { workerRouter } from '../modules/worker/worker.routes.js';
import { securityRouter } from '../modules/security/security.routes.js';
import { onboardingRouter } from '../modules/onboarding/onboarding.routes.js';
import { workspacesRouter } from '../modules/workspaces/workspaces.routes.js';
import { productSurfacesRouter } from '../modules/product-surfaces/product-surfaces.routes.js';
import { customerSettingsRouter } from '../modules/customer-settings/customer-settings.routes.js';
import { teamRouter } from '../modules/team/team.routes.js';
import { launchReadinessRouter } from '../modules/launch-readiness/launch-readiness.routes.js';
import { actionsRouter } from '../modules/actions/actions.routes.js';
import { autonomyRouter } from '../modules/autonomy/autonomy.routes.js';
import { linkedinConnectorRouter } from '../modules/content-publishing/content-connector-credentials.routes.js';
import { notificationPreferencesRouter } from '../modules/notifications/notification-preferences.routes.js';
import { notificationCenterRouter } from '../modules/notifications/notification-center.routes.js';
import { notificationTriggersRouter } from '../modules/notifications/notification-triggers.routes.js';
import { notificationDeepLinksRouter } from '../modules/notifications/notification-deep-links.routes.js';
import { notificationApprovalRemindersRouter } from '../modules/notifications/notification-approval-reminders.routes.js';
import { notificationQuietHoursRouter } from '../modules/notifications/notification-quiet-hours.routes.js';
import { notificationDeliveryLogsRouter } from '../modules/notifications/notification-delivery-logs.routes.js';
import { notificationSecureApprovalLinksRouter } from '../modules/notifications/notification-secure-approval-links.routes.js';
import { notificationQaRouter } from '../modules/notifications/notification-qa.routes.js';
import { approvedContentStyleProfileRouter } from '../modules/content-auto-run/approved-content-style-profile.routes.js';
import { contentRiskScoreRouter } from '../modules/content-auto-run/content-risk-score.routes.js';
import { contentAutoRunDailyCapRouter } from '../modules/content-auto-run/content-auto-run-daily-cap.routes.js';
import { contentAutoRunChannelTimeRouter } from '../modules/content-auto-run/content-auto-run-channel-time.routes.js';
import { contentAutoApprovalDecisionRouter } from '../modules/content-auto-run/content-auto-approval-decision.routes.js';
import { contentFinalPublishValidatorRouter } from '../modules/content-auto-run/content-final-publish-validator.routes.js';
import { contentActionDigestRouter } from '../modules/content-auto-run/content-action-digest.routes.js';
import { contentAnomalyStopRouter } from '../modules/content-auto-run/content-anomaly-stop.routes.js';
import { contentManualOverrideRouter } from '../modules/content-auto-run/content-manual-override.routes.js';
import { contentAutoRunQaRouter } from '../modules/content-auto-run/content-auto-run-qa.routes.js';
import { supportConnectorPlanRouter } from '../modules/support/support-connector-plan.routes.js';
import { supportReadonlyImportRouter } from '../modules/support/support-readonly-import.routes.js';
import { supportTicketSchemaRouter } from '../modules/support/support-ticket-schema.routes.js';
import { supportTicketClassifierRouter } from '../modules/support/support-ticket-classifier.routes.js';
import { supportDraftActionRouter } from '../modules/support/support-draft-action.routes.js';
import { supportPrivacySafeguardsRouter } from '../modules/support/support-privacy-safeguards.routes.js';
import { supportEscalationRulesRouter } from '../modules/support/support-escalation-rules.routes.js';
import { supportSyncStatusRouter } from '../modules/support/support-sync-status.routes.js';
import { supportActionUiRouter } from '../modules/support/support-action-ui.routes.js';
import { supportConnectorQaRouter } from '../modules/support/support-connector-qa.routes.js';
import { supportWriteScopeRouter } from '../modules/support/support-write-scope.routes.js';
import { supportSendExecutorRouter } from '../modules/support/support-send-executor.routes.js';
import { supportManualApprovalGateRouter } from '../modules/support/support-manual-approval-gate.routes.js';
import { supportThreadAssociationRouter } from '../modules/support/support-thread-association.routes.js';
import { supportFaqAutoReplyPolicyRouter } from '../modules/support/support-faq-auto-reply-policy.routes.js';
import { supportBulkSendGuardRouter } from '../modules/support/support-bulk-send-guard.routes.js';
import { supportSensitiveTicketGuardRouter } from '../modules/support/support-sensitive-ticket-guard.routes.js';
import { supportSendResultLogsRouter } from '../modules/support/support-send-result-logs.routes.js';
import { supportRollbackPolicyRouter } from '../modules/support/support-rollback-policy.routes.js';
import { supportSendQaRouter } from '../modules/support/support-send-qa.routes.js';
import { adsConnectorAuditRouter } from '../modules/ads/ads-connector-audit.routes.js';
import { adsWriteScopeRouter } from '../modules/ads/ads-write-scope-planning.routes.js';
import { adsActionTypesRouter } from '../modules/ads/ads-action-types.routes.js';
import { adsBudgetChangePayloadRouter } from '../modules/ads/ads-budget-change-payload.routes.js';
import { adsHardCapsRouter } from '../modules/ads/ads-hard-caps.routes.js';
import { adsManualApprovalExecutorRouter } from '../modules/ads/ads-manual-approval-executor.routes.js';
import { adsBeforeAfterSnapshotRouter } from '../modules/ads/ads-before-after-snapshot.routes.js';
import { adsRollbackExecutorRouter } from '../modules/ads/ads-rollback-executor.routes.js';
import { adsRestrictedAutoRunPolicyRouter } from '../modules/ads/ads-restricted-auto-run-policy.routes.js';
import { adsSafetyQaRouter } from '../modules/ads/ads-safety-qa.routes.js';
import { requestClassifierRouter } from '../modules/orchestrator/request-classifier.routes.js';
import { specialistPromptRegistryRouter } from '../modules/orchestrator/specialist-prompt-registry.routes.js';
import { toolRoutingRouter } from '../modules/orchestrator/tool-routing.routes.js';
import { memorySchemaRouter } from '../modules/orchestrator/memory-schema.routes.js';
import { memoryUiRouter } from '../modules/orchestrator/memory-ui.routes.js';
import { proactivityTriggersRouter } from '../modules/orchestrator/proactivity-triggers.routes.js';
import { voiceInputRouter } from '../modules/orchestrator/voice-input.routes.js';
import { dailyActionDigestRouter } from '../modules/orchestrator/daily-action-digest.routes.js';
import { costAnomalyHardeningRouter } from '../modules/orchestrator/cost-anomaly-hardening.routes.js';
import { v2ReleaseReadinessRouter } from '../modules/orchestrator/v2-release-readiness.routes.js';
import { functionalAuditRouter } from '../modules/orchestrator/functional-audit.routes.js';
import { audienceReachRouter } from '../modules/audience-reach/audience-reach.routes.js';

export const apiV1Router = Router();
const dashboardDataAuth = env.DASHBOARD_REQUIRE_AUTH ? authRequired : optionalAuth;

apiV1Router.use('/health', healthRouter);
apiV1Router.use('/auth', authRouter);
apiV1Router.use('/database', env.NODE_ENV === 'production' ? authRequired : optionalAuth, databaseRouter);
apiV1Router.use('/security', authRequired, securityRouter);
apiV1Router.use('/onboarding', authRequired, onboardingRouter);
apiV1Router.use('/workspaces', authRequired, workspacesRouter);
apiV1Router.use('/product-surfaces', productSurfacesRouter);
apiV1Router.use('/customer-settings', authRequired, customerSettingsRouter);
apiV1Router.use('/team', authRequired, teamRouter);
apiV1Router.use('/launch-readiness', authRequired, launchReadinessRouter);
apiV1Router.use('/actions', authRequired, actionsRouter);
apiV1Router.use('/autonomy', authRequired, autonomyRouter);
apiV1Router.use('/notification-preferences', authRequired, notificationPreferencesRouter);
apiV1Router.use('/notifications', authRequired, notificationCenterRouter);
apiV1Router.use('/notifications', authRequired, notificationTriggersRouter);
apiV1Router.use('/notifications', authRequired, notificationDeepLinksRouter);
apiV1Router.use('/notifications', authRequired, notificationApprovalRemindersRouter);
apiV1Router.use('/notifications', authRequired, notificationQuietHoursRouter);
apiV1Router.use('/notifications', authRequired, notificationDeliveryLogsRouter);
apiV1Router.use('/notifications', authRequired, notificationSecureApprovalLinksRouter);
apiV1Router.use('/notifications', authRequired, notificationQaRouter);

// v0.5.3: local development can keep dashboard reads open, but production automatically requires auth.
apiV1Router.use('/metrics', dashboardDataAuth, metricsRouter);
apiV1Router.use('/audience-reach', dashboardDataAuth, audienceReachRouter);
apiV1Router.use('/chat', env.CHAT_REQUIRE_AUTH ? authRequired : optionalAuth, chatRouter);
apiV1Router.use('/claude', authRequired, claudeRouter);
apiV1Router.use('/brief', dashboardDataAuth, briefRouter);
apiV1Router.use('/weekly', dashboardDataAuth, weeklyRouter);

apiV1Router.use('/admin', authRequired, adminRouter);
apiV1Router.use('/connect/triplewhale', authRequired, tripleWhaleConnectionRouter);
apiV1Router.use('/connect/linkedin', authRequired, linkedinConnectorRouter);
apiV1Router.use('/content-auto-run', authRequired, approvedContentStyleProfileRouter);
apiV1Router.use('/content-auto-run', authRequired, contentRiskScoreRouter);
apiV1Router.use('/content-auto-run', authRequired, contentAutoRunDailyCapRouter);
apiV1Router.use('/content-auto-run', authRequired, contentAutoRunChannelTimeRouter);
apiV1Router.use('/content-auto-run', authRequired, contentAutoApprovalDecisionRouter);
apiV1Router.use('/content-auto-run', authRequired, contentFinalPublishValidatorRouter);
apiV1Router.use('/content-auto-run', authRequired, contentActionDigestRouter);
apiV1Router.use('/content-auto-run', authRequired, contentAnomalyStopRouter);
apiV1Router.use('/content-auto-run', authRequired, contentManualOverrideRouter);
apiV1Router.use('/content-auto-run', authRequired, contentAutoRunQaRouter);
apiV1Router.use('/support', authRequired, supportConnectorPlanRouter);
apiV1Router.use('/support', authRequired, supportReadonlyImportRouter);
apiV1Router.use('/support', authRequired, supportTicketSchemaRouter);
apiV1Router.use('/support', authRequired, supportTicketClassifierRouter);
apiV1Router.use('/support', authRequired, supportDraftActionRouter);
apiV1Router.use('/support', authRequired, supportPrivacySafeguardsRouter);
apiV1Router.use('/support', authRequired, supportEscalationRulesRouter);
apiV1Router.use('/support', authRequired, supportSyncStatusRouter);
apiV1Router.use('/support', authRequired, supportActionUiRouter);
apiV1Router.use('/support', authRequired, supportConnectorQaRouter);
apiV1Router.use('/support', authRequired, supportWriteScopeRouter);
apiV1Router.use('/support', authRequired, supportSendExecutorRouter);
apiV1Router.use('/support', authRequired, supportManualApprovalGateRouter);
apiV1Router.use('/support', authRequired, supportThreadAssociationRouter);
apiV1Router.use('/support', authRequired, supportFaqAutoReplyPolicyRouter);
apiV1Router.use('/support', authRequired, supportBulkSendGuardRouter);
apiV1Router.use('/support', authRequired, supportSensitiveTicketGuardRouter);
apiV1Router.use('/support', authRequired, supportSendResultLogsRouter);
apiV1Router.use('/support', authRequired, supportRollbackPolicyRouter);
apiV1Router.use('/support', authRequired, supportSendQaRouter);
apiV1Router.use('/ads', authRequired, adsConnectorAuditRouter);
apiV1Router.use('/ads', authRequired, adsWriteScopeRouter);
apiV1Router.use('/ads', authRequired, adsActionTypesRouter);
apiV1Router.use('/ads', authRequired, adsBudgetChangePayloadRouter);
apiV1Router.use('/ads', authRequired, adsHardCapsRouter);
apiV1Router.use('/ads', authRequired, adsManualApprovalExecutorRouter);
apiV1Router.use('/ads', authRequired, adsBeforeAfterSnapshotRouter);
apiV1Router.use('/ads', authRequired, adsRollbackExecutorRouter);
apiV1Router.use('/ads', authRequired, adsRestrictedAutoRunPolicyRouter);
apiV1Router.use('/ads', authRequired, adsSafetyQaRouter);
apiV1Router.use('/orchestrator', authRequired, requestClassifierRouter);
apiV1Router.use('/orchestrator', authRequired, specialistPromptRegistryRouter);
apiV1Router.use('/orchestrator', authRequired, toolRoutingRouter);
apiV1Router.use('/orchestrator', authRequired, memorySchemaRouter);
apiV1Router.use('/orchestrator', authRequired, memoryUiRouter);
apiV1Router.use('/orchestrator', authRequired, proactivityTriggersRouter);
apiV1Router.use('/orchestrator', authRequired, voiceInputRouter);
apiV1Router.use('/orchestrator', authRequired, dailyActionDigestRouter);
apiV1Router.use('/orchestrator', authRequired, costAnomalyHardeningRouter);
apiV1Router.use('/orchestrator', authRequired, v2ReleaseReadinessRouter);
apiV1Router.use('/orchestrator', authRequired, functionalAuditRouter);
apiV1Router.use('/triple-whale', authRequired, tripleWhaleRouter);
apiV1Router.use('/refresh-metrics', authRequired, refreshMetricsRouter);
apiV1Router.use('/drafts', authRequired, draftsRouter);
apiV1Router.use('/worker', workerRouter);
