import { env } from '../../config/env.js';
import type { ProductSurfaceModel } from './product-surfaces.types.js';

export function getProductSurfaceModel(): ProductSurfaceModel {
  return {
    version: '0.7.5',
    mode: env.PRODUCT_SURFACE_MODE,
    configuredUrls: {
      publicSiteUrl: env.PUBLIC_SITE_URL,
      appUrl: env.APP_URL,
      adminUrl: env.ADMIN_URL,
      apiUrl: env.API_URL,
    },
    surfaces: [
      {
        key: 'public_site',
        name: 'Public Website',
        localUrl: `${env.PUBLIC_SITE_URL}`,
        productionUrl: 'https://mydomain.com',
        purpose: 'Marketing surface for visitors, feature explanation, trust, pricing later, and signup/login calls to action.',
        audience: 'Visitors, prospects, future customers, and existing customers looking for login.',
        allowedAccess: ['landing page', 'features', 'how it works', 'read-only safety promise', 'pricing placeholder', 'login/start access links'],
        explicitlyForbidden: ['customer metrics', 'workspace data', 'raw payloads', 'admin logs', 'API keys', 'Claude settings'],
        ownsSecrets: false,
        notes: ['This surface must be safe to show publicly.', 'It should never require direct database or secret access.'],
      },
      {
        key: 'customer_app',
        name: 'Customer App',
        localUrl: env.APP_URL,
        productionUrl: 'https://app.mydomain.com',
        purpose: 'Authenticated customer workspace for onboarding, dashboard, Triple Whale connection, AI assistant, briefs, drafts, and customer settings.',
        audience: 'Customers and invited workspace team members.',
        allowedAccess: ['login/signup', 'onboarding', 'dashboard', 'customer settings', 'Triple Whale API-key entry', 'briefs', 'drafts', 'AI chat'],
        explicitlyForbidden: ['other customers data', 'all-workspace admin view', 'raw Claude key', 'worker secret', 'system-wide logs'],
        ownsSecrets: false,
        notes: ['Customers manage their own Triple Whale key here.', 'All data must be scoped to the authenticated workspace.'],
      },
      {
        key: 'internal_admin',
        name: 'Internal Admin',
        localUrl: env.ADMIN_URL,
        productionUrl: 'https://admin.mydomain.com',
        purpose: 'Internal LIFE.SAVER operations panel for customer/workspace monitoring, sync health, usage, worker state, and redacted diagnostics.',
        audience: 'LIFE.SAVER owner and trusted internal operators only.',
        allowedAccess: ['workspace list later', 'connection status', 'sync status', 'usage logs', 'worker logs', 'security/environment status', 'redacted diagnostics'],
        explicitlyForbidden: ['displaying full customer API keys', 'displaying Claude API key', 'editing customer external platforms in v1', 'unapproved destructive actions'],
        ownsSecrets: false,
        notes: ['Admin may monitor connection status but should not reveal raw customer secrets.', 'Admin write powers should be added slowly with audit logs.'],
      },
      {
        key: 'backend_api',
        name: 'Backend API',
        localUrl: env.API_URL,
        productionUrl: 'https://api.mydomain.com',
        purpose: 'Express API that owns authentication, permissions, encrypted connected accounts, Triple Whale sync, Claude calls, briefs, drafts, admin endpoints, and worker endpoints.',
        audience: 'Customer app, admin app, public site for limited safe endpoints, and private worker service.',
        allowedAccess: ['auth endpoints', 'workspace-scoped API endpoints', 'admin endpoints with auth', 'server-side Claude calls', 'encrypted Triple Whale storage', 'worker internal endpoints'],
        explicitlyForbidden: ['returning raw API keys', 'trusting frontend workspace_id without permission checks', 'external write/action-taking AI tools in v1'],
        ownsSecrets: true,
        notes: ['Claude API key belongs to the platform and stays here as an environment secret.', 'Triple Whale customer keys are encrypted here and stored per workspace.'],
      },
      {
        key: 'worker',
        name: 'Private Worker',
        localUrl: 'local process only',
        productionUrl: 'private service only; no public URL',
        purpose: 'Background read-only tasks such as metrics refresh, Daily Brief generation, Weekly Summary generation, and logged internal jobs.',
        audience: 'Internal infrastructure only.',
        allowedAccess: ['read-only metrics refresh', 'brief generation', 'weekly summary generation', 'system event logging'],
        explicitlyForbidden: ['public browser access', 'posting content', 'sending emails', 'changing ad spend', 'campaign edits', 'refunds', 'external write actions'],
        ownsSecrets: true,
        notes: ['Worker endpoints must require WORKER_SHARED_SECRET.', 'Keep scheduled worker disabled locally unless intentionally testing.'],
      },
    ],
    secretOwnership: [
      {
        secret: 'Claude API key',
        owner: 'LIFE.SAVER platform',
        storage: 'Backend/hosting environment variable only',
        managedBy: 'Admin/developer, not customer',
        browserVisibility: 'Never shown in browser; only status/usage may be shown.',
      },
      {
        secret: 'Triple Whale API key',
        owner: 'Each customer workspace',
        storage: 'Encrypted in connected_accounts per workspace',
        managedBy: 'Customer owner/admin from app settings',
        browserVisibility: 'Raw key accepted once for save/update, then never returned. Only key hint/status is shown.',
      },
      {
        secret: 'APP_ENCRYPTION_KEY',
        owner: 'LIFE.SAVER platform/environment',
        storage: 'Protected backend environment variable',
        managedBy: 'Admin/developer only',
        browserVisibility: 'Never shown.',
      },
      {
        secret: 'WORKER_SHARED_SECRET',
        owner: 'LIFE.SAVER platform',
        storage: 'API and worker environment variables',
        managedBy: 'Admin/developer only',
        browserVisibility: 'Never shown.',
      },
    ],
    v1SafetyRules: [
      'LIFE.SAVER remains read + advise + draft only.',
      'No posting, sending, refunds, campaign edits, ad spend changes, product edits, or write-back to external platforms in v1.',
      'Every customer workspace must own and isolate its own Triple Whale connection and metrics.',
      'Claude is platform-owned and server-side only.',
      'Admin views can monitor connection health but must not reveal raw customer or platform secrets.',
    ],
    nextImplementationNotes: [
      'Use these URLs as the source-of-truth product surface map for deployment planning.',
      'v0.7.0 preserves launch readiness and completes V2 Mobile Operator UI Release QA with approval-first operator guardrails, no hidden autonomy, and no automatic external writes.',
      'Use /launch-readiness.html before connecting real domains or inviting a private customer.',
      'Billing should wait until the private customer launch flow is proven stable.',
    ],
  };
}
