export const contentPublishingPlatformPlan = {
  packageName: 'lifesaver-v0.7.0-phase-9-1-choose-first-platform.zip',
  version: '0.7.0',
  phase: 'V2 Phase 9.1 — Choose First Platform',
  healthMode: 'v2-phase-9-1-choose-first-platform',
  selectedPlatform: 'linkedin',
  selectedPlatformLabel: 'LinkedIn',
  selectedInitialAuthorType: 'member',
  selectedInitialContentType: 'text_link_post',
  futureApiFamily: 'LinkedIn Share / UGC Posts',
  manualApprovalRequiredForFuturePublish: true,
  realExecutorAdded: false,
  realExternalWritesAdded: false,
  oauthRoutesAdded: false,
  tokenStorageAdded: false,
  autoRunEnabled: false,
  externalPlatformCalled: false,
  phaseNineTwoNextStep: 'Write Scope Planning for LinkedIn',
  futurePublishGates: [
    'workspace_scoping',
    'manual_approval',
    'permission_guard',
    'master_pause_off',
    'content_pause_off',
    'emergency_safe_mode_off',
    'policy_not_blocked',
    'caps_not_exceeded',
    'idempotency_check',
    'result_log',
    'safe_error_handling',
  ],
} as const;

export type ContentPublishingPlatformPlan = typeof contentPublishingPlatformPlan;
