export const contentPublishingWriteScopePlan = {
  packageName: 'lifesaver-v0.7.0-phase-9-2-write-scope-planning.zip',
  version: '0.7.0',
  phase: 'V2 Phase 9.2 — Write Scope Planning',
  healthMode: 'v2-phase-9-2-write-scope-planning',
  selectedPlatform: 'linkedin',
  selectedPlatformLabel: 'LinkedIn',
  selectedInitialAuthorType: 'member',
  selectedInitialContentType: 'text_link_post',
  requiredProduct: 'Share on LinkedIn',
  requiredWriteScope: 'w_member_social',
  oauthFlow: 'linkedin_3_legged_authorization_code',
  appReviewOrPortalAccessRequired: true,
  manualApprovalRequiredForFuturePublish: true,
  realExecutorAdded: false,
  realExternalWritesAdded: false,
  oauthRoutesAdded: false,
  tokenStorageAdded: false,
  linkedinApiClientAdded: false,
  mediaUploadAdded: false,
  autoRunEnabled: false,
  externalPlatformCalled: false,
  tokenExpiryPlan: {
    doNotAssumeLongLivedAccessTokens: true,
    storeExpiresAtFromExpiresIn: true,
    programmaticRefreshTokensAssumedAvailable: false,
    reconnectRequiredIfExpiredWithoutRefresh: true,
    futureRefreshTokenStorageMustBeEncrypted: true,
  },
  publishingPermissionPlan: {
    memberPostingAllowedFuture: true,
    organizationPostingAllowedFuture: false,
    sponsoredContentAllowedFuture: false,
    commentsLikesAutomationAllowedFuture: false,
    bulkPublishAllowedFuture: false,
  },
  mediaUploadLimitations: {
    mediaUploadAddedThisPhase: false,
    initialExecutorShouldBeTextLinkOnly: true,
    imageUploadLaterRequiresAssetOrImagesFlow: true,
    knownImageFormats: ['jpg', 'gif', 'png'],
    knownImagePixelLimitLessThan: 36152320,
    gifMaxFrames: 250,
    videoUploadLaterSeparateFlow: true,
    documentUploadLaterSeparateFlow: true,
    organicCarouselOutOfInitialScope: true,
  },
  futurePublishGates: [
    'workspace_scoping',
    'manual_approval',
    'permission_guard',
    'master_pause_off',
    'content_pause_off',
    'emergency_safe_mode_off',
    'policy_not_blocked',
    'caps_not_exceeded',
    'token_valid',
    'payload_valid',
    'idempotency_check',
    'result_log',
  ],
  phaseNineThreeNextStep: 'Connector Credential Model for LinkedIn',
} as const;

export type ContentPublishingWriteScopePlan = typeof contentPublishingWriteScopePlan;
